AttributeError: module 'gym_duckietown.tasks.lf_challenge.solutions.solution' has no attribute 'LfChallengeTaskSolution'
False: Non-zero return code, probably a syntax error occurred\ntime=1603127528.7499564 gym-duckietown 2019.0.0

time=1603127530.8851097 Registering gym environment id: Duckietown-4way-v0
time=1603127530.8862424 Registering gym environment id: Duckietown-loop_dyn_duckiebots-v0
time=1603127530.88724 Registering gym environment id: Duckietown-loop_empty-v0
time=1603127530.8887742 Registering gym environment id: Duckietown-loop_obstacles-v0
time=1603127530.890728 Registering gym environment id: Duckietown-loop_pedestrians-v0
time=1603127530.8922634 Registering gym environment id: Duckietown-small_loop-v0
time=1603127530.8934398 Registering gym environment id: Duckietown-small_loop_cw-v0
time=1603127530.8952866 Registering gym environment id: Duckietown-straight_road-v0
time=1603127530.899939 Registering gym environment id: Duckietown-straight_road_10_tiles_no_start_tile-v0
time=1603127530.9016283 Registering gym environment id: Duckietown-straight_road_no_start_tile-v0
time=1603127530.9029877 Registering gym environment id: Duckietown-straight_road_trafficlight-v0
time=1603127530.9037097 Registering gym environment id: Duckietown-straight_road_with_side_floor-v0
time=1603127530.9068809 Registering gym environment id: Duckietown-udem1-v0
time=1603127530.909266 Registering gym environment id: Duckietown-zigzag_dists-v0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/lf_challenge/checker.py", line 6, in <module>
    checkers=[StopAtCoordinatesChecker(), RewardChecker()]
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/solution_evaluator.py", line 33, in __init__
    self.solution_class = getattr(solution_file_as_module, solution_class_name)
AttributeError: module 'gym_duckietown.tasks.lf_challenge.solutions.solution' has no attribute 'LfChallengeTaskSolution'
